services:
  canteen-docker:
    container_name: canteen-docker
    build: .
    volumes:
      - ./membership-canteen:/var/www/html
    ports:
      - 8000:80

  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: canteen
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3371:3306
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1